services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - DEBUG=true
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sequelize-sandbox
