services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - DEBUG=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sandbox-db
