name: Run Unit & Integration tests

on:
  push

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Service
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test

  integration:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Service
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm ci
      - name: Run Integration Tests
        run: npm run test:integration